// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lppdmirduhvoubjlbxik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwcGRtaXJkdWh2b3ViamxieGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NDA1NTYsImV4cCI6MjA4NjAxNjU1Nn0.TZe_6BquCEJb2QiMDXf726QDBBl_sJepJ9MsV5KoWMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Enable automatic session detection from URL hash
  }
});